<?php
/**
 * Copyright © 2015-2021, Cacholong <info@cacholong.nl>
 *
 * This file is part of Cache Control
 *
 * Cache Control is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Cache Control is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Cache Control.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php defined('ABSPATH') OR exit; ?>
<?php
/**
 * Template for field 'location json hosts file'
 * 
 * @author      Preliot, Piet Rol <info@preliot.nl> (commissioned by Cacholong)
 * @copyright   Cacholong <info@cacholong.nl>
 * 
 * @version     1.0.0     Created at 2015-10-21
 */
?>
<input id="<?php echo \Cacholong\Entities\Identifier::CC_FIELD_HOSTS_FILE ?>" name="<?php echo \Cacholong\Entities\Identifier::CC_FIELD_HOSTS_FILE ?>" type="text" class="large-text" value="<?php echo get_option(\Cacholong\Entities\Identifier::CC_FIELD_HOSTS_FILE)?>" />
<p class="description">(<?php _e('Url or relative file path allowed', \Cacholong\Entities\Identifier::CC_TEXT_DOMAIN) ?>)</p>