<?php
/**
 * Copyright © 2015-2021, Cacholong <info@cacholong.nl>
 *
 * This file is part of Cache Control
 *
 * Cache Control is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Cache Control is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Cache Control.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php defined('ABSPATH') OR exit;?>
<?php
/**
 * Template for field 'remove_style_id'
 *
 * @author      Preliot, Piet Rol <info@preliot.nl> (commissioned by Cacholong)
 * @copyright   Cacholong <info@cacholong.nl>
 *
 * @version     1.0.0     Created at 2017-12-15
 *
 */

$remove_style_id = \Cacholong\Entities\Identifier::CC_FIELD_REMOVE_STYLE_ID;
?>
<input type="checkbox" id="<?php echo $remove_style_id?>" name="<?php echo $remove_style_id?>" <?php echo cacholong_cc_checkbox_checked_attribute(get_option($remove_style_id))?> />
<label for="<?php echo $remove_style_id?>"><?php _e('Remove id tag (frontend)', \Cacholong\Entities\Identifier::CC_TEXT_DOMAIN)?></label>
<p class="description">(<?php _e('Pagespeed can optimize css performance on frontend by removing id tag from stylesheets. Setting is ignored when user is seeing admin bar or is using admin page, to prevent issues with other plugins.', \Cacholong\Entities\Identifier::CC_TEXT_DOMAIN)?>)</p>